import { ProjectEntity, ProjectAlias, MeetingAlias, ContactEntity } from "./types";

export const INITIAL_PROJECTS: ProjectEntity[] = [
  {
    entity_name: "eStride Digital",
    relationship_type: "Internal",
    parent_relationship: null,
    status: "Active",
    basecamp_project_name: "eStride",
    basecamp_project_id: "5463662",
    list_routing_profile: null,
    notes: "Internal/default project for general tasks and triage",
  },
  {
    entity_name: "FOOGO Green",
    relationship_type: "Direct Client",
    parent_relationship: null,
    status: "Active",
    basecamp_project_name: "FOOGO Green",
    basecamp_project_id: "29607162",
    list_routing_profile: "FOOGO Green List Routing Profile v1",
    notes: "Direct eco-friendly tableware client; uses 8 approved lists",
  },
  {
    entity_name: "BOLDEST",
    relationship_type: "Client / White-label Partner",
    parent_relationship: null,
    status: "Active",
    basecamp_project_name: "BOLDEST",
    basecamp_project_id: "31049281",
    list_routing_profile: null,
    notes: "Also acts as a delivery channel for downstream end-clients",
  },
  {
    entity_name: "Unifi",
    relationship_type: "BOLDEST End Client",
    parent_relationship: "BOLDEST",
    status: "Active",
    basecamp_project_name: "Unifi",
    basecamp_project_id: "31448291",
    list_routing_profile: null,
    notes: "Mutual fund client delivered through BOLDEST partnership",
  },
  {
    entity_name: "Shopware",
    relationship_type: "BOLDEST End Client",
    parent_relationship: "BOLDEST",
    status: "Active",
    basecamp_project_name: "Shopware",
    basecamp_project_id: "31889201",
    list_routing_profile: null,
    notes: "E-commerce platform engagement delivered through BOLDEST",
  },
  {
    entity_name: "eFin",
    relationship_type: "BOLDEST End Client",
    parent_relationship: "BOLDEST",
    status: "Pipeline",
    basecamp_project_name: null,
    basecamp_project_id: null,
    list_routing_profile: null,
    notes: "Opportunity work routes to eStride until engagement is active",
  },
  {
    entity_name: "NOVOS FiBER",
    relationship_type: "BOLDEST End Client",
    parent_relationship: "BOLDEST",
    status: "Pipeline",
    basecamp_project_name: null,
    basecamp_project_id: null,
    list_routing_profile: null,
    notes: "Opportunity work routes to eStride until engagement is active",
  },
  {
    entity_name: "AT&T",
    relationship_type: "BOLDEST End Client",
    parent_relationship: "BOLDEST",
    status: "Pipeline",
    basecamp_project_name: null,
    basecamp_project_id: null,
    list_routing_profile: null,
    notes: "Opportunity work routes to eStride until engagement is active",
  },
  {
    entity_name: "FamilyGuard",
    relationship_type: "BOLDEST End Client",
    parent_relationship: "BOLDEST",
    status: "Pipeline",
    basecamp_project_name: null,
    basecamp_project_id: null,
    list_routing_profile: null,
    notes: "Opportunity work routes to eStride until engagement is active",
  },
  {
    entity_name: "Sandiva",
    relationship_type: "Direct Client",
    parent_relationship: null,
    status: "Inactive",
    basecamp_project_name: "Sandiva",
    basecamp_project_id: "28114092",
    list_routing_profile: null,
    notes: "Historical project; tasks routed to eStride for manager review",
  },
];

export const INITIAL_PROJECT_ALIASES: ProjectAlias[] = [
  { entity_name: "FOOGO Green", alias: "FOOGO", alias_type: "Short Name" },
  { entity_name: "FOOGO Green", alias: "FUCO Green", alias_type: "Transcript Variant" },
  { entity_name: "BOLDEST", alias: "The Boldest", alias_type: "Name Variant" },
  { entity_name: "BOLDEST", alias: "theboldest.ai", alias_type: "Domain" },
  { entity_name: "Unifi", alias: "Unifi MF", alias_type: "Project Name" },
  { entity_name: "Unifi", alias: "Unifi Mutual Fund", alias_type: "Name Variant" },
  { entity_name: "Unifi", alias: "Unify", alias_type: "Transcript Variant" },
  { entity_name: "Unifi", alias: "Unify Mutual Fund", alias_type: "Transcript Variant" },
  { entity_name: "NOVOS FiBER", alias: "NOVOS", alias_type: "Short Name" },
  { entity_name: "NOVOS FiBER", alias: "Novos Fiber", alias_type: "Name Variant" },
  { entity_name: "AT&T", alias: "ATT", alias_type: "Acronym / Transcript Variant" },
  { entity_name: "FamilyGuard", alias: "FamilyGuard", alias_type: "Short Name" },
  { entity_name: "FamilyGuard", alias: "Tom Avelino", alias_type: "Key Stakeholder Name" },
  { entity_name: "eStride Digital", alias: "eStride", alias_type: "Short Name" },
];

export const INITIAL_MEETING_ALIASES: MeetingAlias[] = [
  {
    meeting_alias: "FOOGO Green x eStride - Weekly Governance Call",
    entity_name: "FOOGO Green",
    meeting_context: "External - Single Project",
  },
  {
    meeting_alias: "FOOGO Green - Blog Planning [Internal]",
    entity_name: "FOOGO Green",
    meeting_context: "Internal - Single Project",
  },
  {
    meeting_alias: "eStride Daily Standup",
    entity_name: "eStride Digital",
    meeting_context: "Internal - Multi-Project",
  },
  {
    meeting_alias: "eStride - Standup",
    entity_name: "eStride Digital",
    meeting_context: "Internal - Multi-Project",
  },
];

export const INITIAL_CONTACTS: ContactEntity[] = [
  { full_name: "Divya Sudalaikkan", name_alias: "Divya", entity_name: "FOOGO Green", notes: "FOOGO client stakeholder" },
  { full_name: "Dilip Keshu", name_alias: "Dilip", entity_name: "BOLDEST", notes: "BOLDEST partner lead (Context-dependent)" },
  { full_name: "Keith Pires", name_alias: "Keith", entity_name: "BOLDEST", notes: "BOLDEST partner contact (Context-dependent)" },
  { full_name: "Scott Allen", name_alias: "Scott", entity_name: "BOLDEST", notes: "BOLDEST partner contact (Context-dependent)" },
  { full_name: "Aman Reddy", name_alias: "Aman", entity_name: "Unifi", notes: "Unifi client stakeholder" },
  { full_name: "Meera Nair", name_alias: "Meera", entity_name: "Unifi", notes: "Unifi client stakeholder" },
  { full_name: "George Fernandes", name_alias: "George", entity_name: "Unifi", notes: "Unifi client stakeholder" },
  { full_name: "Ramy G. Youssef", name_alias: "Ramy", entity_name: "BOLDEST", notes: "BOLDEST technical partner" },
  { full_name: "Sydney Maringas", name_alias: "Sydney", entity_name: "BOLDEST", notes: "BOLDEST account manager" },
  { full_name: "Pradeep Agnihotri", name_alias: "Pradeep A", entity_name: "BOLDEST", notes: "External partner Pradeep (distinguished from Pradeep G)" },
];

export const FOOGO_APPROVED_LISTS = [
  "Marketing Automation",
  "Paid Media",
  "Website",
  "Content",
  "SEO & AEO",
  "Analytics & Reporting",
  "Operations",
  "Requires Routing",
];

export const TEAM_MEMBERS = [
  { name: "Pradeep G", aliases: ["pradeep", "pg", "pradeep g"], role: "Delivery Lead", id: "38921" },
  { name: "Hari Prasad", aliases: ["hari", "hp", "hariprasad", "hari prasad"], role: "Marketing & Strategy", id: "38922" },
  { name: "Praveen Kumar", aliases: ["praveen", "kumar", "praveenkumar"], role: "Media & Ops", id: "38923" },
  { name: "Karthik R", aliases: ["karthik", "kartik", "karthikr"], role: "Analytics Lead", id: "38924" },
  { name: "Govind S", aliases: ["govind", "govindaraj", "govind s"], role: "Tech & Dev Lead", id: "38925" },
  { name: "Kannan K", aliases: ["kannan", "kannan k"], role: "Shopify / Dev", id: "38926" },
  { name: "Freya", aliases: ["freya"], role: "Content & Copy", id: "38927" },
  { name: "Sydney", aliases: ["sydney", "sidney"], role: "Operations", id: "38928" },
];
